### ISSUE TITLE
Support non root path installation

### ISSUE THREAD

**Issue by opi** [YunoHost-Apps/haste_ynh#1]
It seems that issue could be solved, see 
- https://github.com/seejohnrun/haste-server/issues/53
- https://github.com/seejohnrun/haste-server/issues/46
- http://www.ctrl-alt-del.cc/2014/11/haste-server-base-url-hackpatch.html

**Comment by beanface42** [comment]
Hi There,

Is there any chance that the possibility to install the beautiful tool on a non-root path to be available without knick-knacking with Nginx in the future?

Best regards.

**Comment by ericgaspar** [comment]
Closing. There is not much going on upstream concerning that matter...
