### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost-Apps/haste_ynh#2]
Hi,

Your app doesn't work for the moment.
It's fail on the installation tests on our CI.
https://ci-apps.yunohost.org/jenkins/job/haste%20(Community)/6/consoleFull

Your app will be moved at 'notworking' status by the next week, on 15 of july.

**Comment by nicofrand** [comment]
Seems like the issue was fixed : https://github.com/YunoHost/apps/pull/361.
This ticket should probably be closed ?
